services:
  - type: web
    name: finansys-core-api
    runtime: node
    buildCommand: npm install --production
    startCommand: node src/main.js
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
